---
title: "Projects"
format: html
---

Welcome! Here are some of my projects. Click the GitHub icon to see the source code.

---

## Deutschlernen

Anki inspierd python application developed with PyQt.
[GitHub 🔗](https://github.com/edo98811/Deutschlernen.git)

---

## Maps posters

When you want to nice map of a place that's dear to you but don't want to pay.
[GitHub 🔗](https://github.com/edo98811/Map.git)

---

## rbioinfo r-package
A collection of functions to help building reports in Rmarkdown or quarto.  
[GitHub 🔗](https://github.com/edo98811/helper-functions-rbioinfo.git)

---

## rbioinfo r-package
A collection of functions to help building reports in Rmarkdown.  
[GitHub 🔗](https://github.com/edo98811/helper-functions-rbioinfo.git)

---

## cdt_to_se
An interface to convert Metabolon data table objects to SingleCellExperiment objects.  
[GitHub 🔗](https://github.com/edo98811/metabolon_summarized_experiment.git)

---

## Perspective correction and object annotation 

To assist in the boring task for a the data analysis needed for a paper.
Publication:
[GitHub 🔗](https://github.com/edo98811/WiMa2025.git)


---

## WiMa_app
An application to represent our institute in the wissenschaftsmarkt 2025 in Mainz. 
Developed with:  
[GitHub 🔗](https://github.com/edo98811/WiMa2025.git)

---

## single cell pipeline
A pipeline to simplify the analysis of single-cell RNA-seq data.  
[GitHub 🔗](https://github.com/edo98811/single-cell-pipeline)

---

## fs-docker
A Python package to automate execution of freesurfer pipelines using docker.  
[GitHub 🔗](https://github.com/edo98811/fs-docker)

---

## celescope processing
A Python package to simplify the processing of single-cell RNA-seq data (my first interaction with bioinformatics).  
[GitHub 🔗](https://github.com/edo98811/celescope-preprocessing)

---

## Lux-meter
A light intensity measurement tool written in Assembly language, made to work on an atmega.  
[GitHub 🔗](https://github.com/edo98811/Lux-meter.git)

---

## IoT project
An IoT-based platform to manage multiple sensors.  
[GitHub 🔗](https://github.com/edo98811/IoT-project.git)

---

## Master thesis data analysis
The code I wrote to analyze the data I used in my master thesis.  
[GitHub 🔗](https://github.com/edo98811/master-thesis-data-analysis.git)

---

## 3D Graphics Exergame
Made with Unity.  
[GitHub 🔗](https://github.com/edo98811/Progetto-Unity-Git.git)

---

## Temperature monitoring webapp
A webapp based on Flask extended as university project.  
[GitHub 🔗](https://github.com/edo98811/temperature-measure-webapp.git)
